coverage:
  status:
    project: yes
    patch: yes

  comment:
    layout: "reach, diff, flags, files"
    show_critical_paths: true

  profiling:
    critical_files_paths:
      - api/calculator.py

  notify:
    slack:
      default:
        url: ${{ secrets.SLACK_WEBHOOK_URL }}
        only_pulls: false
        base:
          - "auto"