coverage:
  status:
    project: yes
      # default:
      #   target: 100%
      #   threshold: 1%
    patch: yes


comment:
  layout: "reach, diff, flags, files"
  show_critical_paths: true

profiling:
  critical_files_paths:
    - api/calculator.py