coverage:
  status:
    project: yes
    patch: yes

  comment:
    layout: "reach, diff, flags, files"
    show_critical_paths: true

  profiling:
    critical_files_paths:
      - api/calculator.py

  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        only_pulls: true
        branches: 
          - "main"
        paths: 
          - "api"